### ISSUE TITLE
still getting error

### ISSUE THREAD

**Issue by askfriends** [iamLiquidX/SearchX#6]
still getting error
`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'`

**Comment by iamLiquidX** [comment]
Please re-read deploy guide. You have to remove the first line with that with # both from authorized chats and drive_folder and the ln fill ur values.

> still getting error `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter'`

**Comment by askfriends** [comment]
ok bro done that but now getting this error, and when i run /search kishore it returns "Searching..." msg and nothing happens

`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2021-10-14 12:00:27,203 - bot - INFO - Yeah I'm running!
2021-10-14 12:00:31,042 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:31,043 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:35,288 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:35,289 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:42,228 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:42,229 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:48,174 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-10-14 12:00:48,174 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

**Comment by iamLiquidX** [comment]
> ok bro done that but now getting this error, and when i run /search kishore it returns "Searching..." msg and nothing happens
> 
> `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) 2021-10-14 12:00:27,203 - bot - INFO - Yeah I'm running! 2021-10-14 12:00:31,042 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:31,043 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception. Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry if not action_cb(): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb updates = self.bot.get_updates(self.last_update_id, File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator result = func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates result = self._request.post(url, data, timeout=float(read_latency) + float(timeout)) File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post result = self._request_wrapper('POST', url, File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper raise Conflict(message) telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:35,288 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:35,289 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception. Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry if not action_cb(): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb updates = self.bot.get_updates(self.last_update_id, File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator result = func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates result = self._request.post(url, data, timeout=float(read_latency) + float(timeout)) File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post result = self._request_wrapper('POST', url, File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper raise Conflict(message) telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:42,228 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:42,229 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception. Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry if not action_cb(): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb updates = self.bot.get_updates(self.last_update_id, File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator result = func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates result = self._request.post(url, data, timeout=float(read_latency) + float(timeout)) File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post result = self._request_wrapper('POST', url, File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper raise Conflict(message) telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:48,174 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running 2021-10-14 12:00:48,174 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception. Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry if not action_cb(): File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 338, in polling_action_cb updates = self.bot.get_updates(self.last_update_id, File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 70, in decorator result = func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2136, in get_updates result = self._request.post(url, data, timeout=float(read_latency) + float(timeout)) File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 331, in post result = self._request_wrapper('POST', url, File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 249, in _request_wrapper raise Conflict(message) telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

Revoke ur bot token. Generator a new one. Add that to config. Also whenever you make change to repo railway deploys new container in the same app. Delete the old container.

**Comment by askfriends** [comment]
bro plz dont close the issue until its resolved completely, i really appreciate ur help.
I deleted railway app and deployed again, it went good but when i run /start command i get two WELCOME replies. And when i enter /search -d command i get two responses saying "Searching..." but then nothing appears, I'm new to railway and this is my first app on railway so kindly guide me how to delete duplicate container?  
![railway](https://user-images.githubusercontent.com/2517219/137335846-daa1ca90-48d5-4849-9db6-111887ab11db.jpg)

**Comment by askfriends** [comment]
im attaching my config files here
![BollywoodSongsBot2](https://user-images.githubusercontent.com/2517219/137338438-58dcef6a-0d69-4996-a81b-c84fb13e2da8.jpg)
![BollywoodSongsBot3](https://user-images.githubusercontent.com/2517219/137338442-ce3d8d2c-2b72-4bef-a220-f07c76a2e323.jpg)

![BollywoodSongsBot](https://user-images.githubusercontent.com/2517219/137338423-50da9ee6-5c75-4bee-b6d3-27e9267c25bc.jpg)
![Web capture_14-10-2021_193655_railway app](https://user-images.githubusercontent.com/2517219/137340517-055b706f-6a69-46f9-98b4-257cbdd2da30.jpeg)

**Comment by iamLiquidX** [comment]
> bro plz dont close the issue until its resolved completely, i really appreciate ur help. I deleted railway app and deployed again, it went good but when i run /start command i get two WELCOME replies. And when i enter /search -d command i get two responses saying "Searching..." but then nothing appears, I'm new to railway and this is my first app on railway so kindly guide me how to delete duplicate container? ![railway](https://user-images.githubusercontent.com/2517219/137335846-daa1ca90-48d5-4849-9db6-111887ab11db.jpg)

Read carefully...

Issue is not bot side that's i closed the issue. Here is a 
solution you can try.
Revoke ur token. But don't add this to config yet.
Go railway, go dashboard, click on ur project of searchx , then click on deployment, now delete all the deployments. Wait a minute or two then go to ur repo edit ur config and that bot token to config.env and save. Railway will auto start a new deployment. And there will be no error.

**Comment by iamLiquidX** [comment]
> im attaching my config files here ![BollywoodSongsBot2](https://user-images.githubusercontent.com/2517219/137338438-58dcef6a-0d69-4996-a81b-c84fb13e2da8.jpg) ![BollywoodSongsBot3](https://user-images.githubusercontent.com/2517219/137338442-ce3d8d2c-2b72-4bef-a220-f07c76a2e323.jpg)
> 
> ![BollywoodSongsBot](https://user-images.githubusercontent.com/2517219/137338423-50da9ee6-5c75-4bee-b6d3-27e9267c25bc.jpg) ![Web capture_14-10-2021_193655_railway app](https://user-images.githubusercontent.com/2517219/137340517-055b706f-6a69-46f9-98b4-257cbdd2da30.jpeg)

This one is showing that you have entered wrong bot token.

**Comment by askfriends** [comment]
ok bro i did, revoked token, deleted deployment from railway, then edit config.env and entered new token, but still getting same error
`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2021-10-15 06:24:03,614 - bot - INFO - Yeah I'm running!
2021-10-15 06:24:49,538 - bot - INFO - UID: 1271425814 - UN: user700 - MSG: /start
2021-10-15 06:24:49,538 - bot - INFO - UID: 1271425814 - UN: user700 - MSG: /start
2021-10-15 06:25:07,799 - bot - INFO - Searching: kishore
2021-10-15 06:25:07,814 - bot - INFO - Searching: kishore
2021-10-15 06:25:07,855 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/list.py", line 20, in list_drive
    gdrive = GoogleDriveHelper(None)
  File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 27, in __init__
    self.__service = self.authorize()
  File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 53, in authorize
    credentials.refresh(Request())
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 300, in refresh
    ) = reauth.refresh_grant(
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/reauth.py", line 345, in refresh_grant
    _client._handle_error_response(response_data)
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/_client.py", line 58, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
2021-10-15 06:25:07,860 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/list.py", line 20, in list_drive
    gdrive = GoogleDriveHelper(None)
  File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 27, in __init__
    self.__service = self.authorize()
  File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 53, in authorize
    credentials.refresh(Request())
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 300, in refresh
    ) = reauth.refresh_grant(
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/reauth.py", line 345, in refresh_grant
    _client._handle_error_response(response_data)
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/_client.py", line 58, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})`

**Comment by iamLiquidX** [comment]
> ok bro i did, revoked token, deleted deployment from railway, then edit config.env and entered new token, but still getting same error `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) 2021-10-15 06:24:03,614 - bot - INFO - Yeah I'm running! 2021-10-15 06:24:49,538 - bot - INFO - UID: 1271425814 - UN: user700 - MSG: /start 2021-10-15 06:24:49,538 - bot - INFO - UID: 1271425814 - UN: user700 - MSG: /start 2021-10-15 06:25:07,799 - bot - INFO - Searching: kishore 2021-10-15 06:25:07,814 - bot - INFO - Searching: kishore 2021-10-15 06:25:07,855 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run self._result = self.pooled_function(*self.args, **self.kwargs) File "/usr/src/app/bot/modules/list.py", line 20, in list_drive gdrive = GoogleDriveHelper(None) File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 27, in __init__ self.__service = self.authorize() File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 53, in authorize credentials.refresh(Request()) File "/usr/local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 300, in refresh ) = reauth.refresh_grant( File "/usr/local/lib/python3.9/site-packages/google/oauth2/reauth.py", line 345, in refresh_grant _client._handle_error_response(response_data) File "/usr/local/lib/python3.9/site-packages/google/oauth2/_client.py", line 58, in _handle_error_response raise exceptions.RefreshError(error_details, response_data) google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'}) 2021-10-15 06:25:07,860 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run self._result = self.pooled_function(*self.args, **self.kwargs) File "/usr/src/app/bot/modules/list.py", line 20, in list_drive gdrive = GoogleDriveHelper(None) File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 27, in __init__ self.__service = self.authorize() File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 53, in authorize credentials.refresh(Request()) File "/usr/local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 300, in refresh ) = reauth.refresh_grant( File "/usr/local/lib/python3.9/site-packages/google/oauth2/reauth.py", line 345, in refresh_grant _client._handle_error_response(response_data) File "/usr/local/lib/python3.9/site-packages/google/oauth2/_client.py", line 58, in _handle_error_response raise exceptions.RefreshError(error_details, response_data) google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})`

Double check its still bot token issue. U may have revoked the bot token of another bot.

**Comment by askfriends** [comment]
ok bro here is the update, i regenrated token.pickle and uploaded it to repo, Now it seems fine but when i search for /search kishore i get this error, how to fix that now?

`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2021-10-15 07:19:18,289 - bot - INFO - Yeah I'm running!
2021-10-15 07:19:36,141 - bot - INFO - UID: 1271425814 - UN: user700 - MSG: /start
2021-10-15 07:19:46,104 - bot - INFO - Searching: kishore
2021-10-15 07:20:52,171 - bot.helper.drive_utils.gdriveTools - INFO - my a: 90
2021-10-15 07:20:53,463 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/list.py", line 21, in list_drive
    msg, button = gdrive.drive_list(search)
  File "/usr/src/app/bot/helper/drive_utils/gdriveTools.py", line 199, in drive_list
    self.path.append(telegra_ph.create_page(title = 'SearchX',
  File "/usr/local/lib/python3.9/site-packages/telegraph/api.py", line 164, in create_page
    return self._telegraph.method('createPage', values={
  File "/usr/local/lib/python3.9/site-packages/telegraph/api.py", line 37, in method
    raise TelegraphException(response.get('error'))
telegraph.exceptions.TelegraphException: CONTENT_TOO_BIG`

then i changed 90 to 50 in `bot/helper/drive_utils/gdriveTools.py` and it worked.

Now i have three questions:
1. It wont show all results? i got this msg in telegram
`Found 50 results. (Only showing top 90 results. Omitting remaining results)`

2. Kindly mention all available commands.
3. And can i disable Google Drive Link in search result page? I want to show only index link.

**Comment by iamLiquidX** [comment]
All results can never be shown if the number is too high dur to telegraph api limit
U can check commands.py for commands
U have to edit the code if u only wanna show gdrive links.
